language: node_js
node_js:
- 6
- node
sudo: false
cache:
  directories:
  - node_modules
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm install -g bower istanbul
- bower install
script: gulp test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: cX9tftMlCt1xl6bV8b5ehSic3ihigd68QvQIVoxuOuyNeTr1yVGqMI+dF29MoMqU/P4zW2jJbgoZMwNn4wYaKvfhVztanVuneknD1vkZMppwbEJ5sj+r17Tdg0jzvZHWomEoW265MC722H7aCNyQVS7qDRBdWAVs+Y44LHp6cvJZNsCHidFarcHJg39p6EkyfAUTNlRuPJt8hhnV9aNjClTP1AX1es+XOZibvD1NpLLwDMVvXH/U0JVa/gIECkoMZTWPAah9yHImooyc3N7U5Fpy4NfjUkx8L8iRYGXgrvffk+glsZD5PERCRMRxp+vHp6Co82dBG2wk3eDP4s1Q+iKGSSSDTueJbWpw/wQJy98YCXD79zr0yyF4pC4DanDnvwASAA+8El2Nl3v/vtnZHaU/0j8yPAp1yNVdZpQkvRBRgkPHhnaiTANPgOrIEApwZQBNfIEsoy8mUqkJujHQhdKqIeTg4lX5Putha86E/3t6IWSbWexXbo3jr4KvaidnxLLQI778aCeuTuSw6apupqnVWT82AE6KO17xSVDDfvf+sLQjgPVJBtgyK5gfYxCiEBu0NQwLql3HFaJ/RY2NwqmGhoQ4hnBBauBbA9rK3hplZ3kUeUhW4Ox9yRTX7vOX0YeWRiFNeQwbS+ICeTrx8heP+/VI98R8oIAtlrcKVB4=
  app: jkitchen
  on:
    repo: andela-joladimeji/jkitchen
    branch: master
env:
  matrix:
    secure: LwsFya3D8+Sf6+K7YsQVrmNZc9WEnbgBXb9Z2sJM9ILL21Qf+tnKdEnmeagneDZ2VGfTWhW3KFiACohddW7cmzvRNLA6KGzehfNdfYLrd0rp2ENJOjrDWED2fRxD/KDjF/6ICvYhD8jPbPt5S2qJNeg+YBCP7FUEfa+/sOmyg4llJlxGAGppnV/K9n0cXdufho8g1iYk4kwzW8wejmsW/jDQ7PIB/zbNyvC3opuymP9aCcGJ2X6cHeqNxTpToEWLOsQ/1Dsxy36HAZhcCnqO2UCOeOEhT9N0tS3EW35HBQQq3jn7GemmqwuiHDXn4NiKlYZWAzuRZJiyYuXvxd5IwX8KJUrOeXE6M7xur4DDTzcOEr+tdY3i/6tFEI0DBLigO/Q3EVuaoX3lkkeeFjTCnNMTV+IQEoTiH1kuizNx28brvHq0IdFeDc4LscwZajDF5zYJX6grnezMvphYlIWhj3k/gjszKK5Qu7+Zws+cK4F8iGn8JTAxdZpCxjoxm632KgL17wIC5zgPixkSllUq+uwR/oQ+dF26vhZZmx2NRbnlyCENQMmD+7T4LH1f0fyHDrCw91LMQstiIP8mUsshyE93QnJcjGR/KAGFwAXVu0lbyV7bAkgrv9AWqqqkgIiJhYYpF4Hl2q1vHmyzJhdEHW4Lt7ivKke1Ukr7LLzT9IU=
