language: node_js
node_js:
  - 6
  - node
sudo: false
script: 
  - istanbul cover ./node_modules/mocha/bin/_mocha tests/server/*.js --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
cache:
  directories:
    - "node_modules"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
    - npm install -g bower istanbul
    - bower install
